spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_data?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: book
server:
  port: 8181