server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lakshanrajasuriya/booking-config
          search-paths:
            - 'service-config/*service'